version: '2'

services:
    logservices:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        links:
            - db
        container_name: web
        ports:
            - "35001:35001"
    db:
        image: mongo:latest
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: